apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: langflow
  labels:
    app: langflow
spec:
  to:
    kind: Service
    name: langflow-external
    weight: 100
  port:
    targetPort: proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
