apiVersion: v1
kind: Service
metadata:
  name: langflow-external
  labels:
    app: langflow
spec:
  selector:
    app: langflow-service
    release: langflow
  ports:
  - name: proxy
    port: 4180
    targetPort: oauth-proxy
    protocol: TCP
  type: ClusterIP
