apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: langflow-service
spec:
  template:
    spec:
      volumes:
        - name: gcloud-adc
          secret:
            secretName: gcloud-adc
            optional: true
      containers:
        - name: langflow-ide
          envFrom:
            - secretRef:
                name: langflow-credentials
                optional: true
          volumeMounts:
            - name: gcloud-adc
              mountPath: /var/secrets/gcloud
              readOnly: true
