apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# PostgreSQL deployment
# Requires: postgres-secret (created by overlay)

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: deep-research
