apiVersion: v1
kind: Service
metadata:
  name: deep-research
  labels:
    app: deep-research
spec:
  selector:
    app: deep-research
  ports:
  - name: public
    port: 4180
    targetPort: 4180
  type: ClusterIP
