apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: multi-agent-platform
  labels:
    app: multi-agent-platform
spec:
  to:
    kind: Service
    name: multi-agent-platform
  port:
    targetPort: public
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
